language: c

compiler:
  - gcc
  - clang

os:
  - linux
  
jobs:
  include:
  - os: osx
    osx_image: xcode11
    compiler: clang
    env: 
    - PATH=$PATH:/usr/local/Cellar/gettext/0.21/bin
    before_install:
    - ls -alr /usr/local/Cellar/gettext/0.20.1
    - ls -alr /usr/local/opt/gettext/0.20.1
  exclude:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake-1.15
    - autopoint
    - bison
    - gcc-6
    - gettext
    - help2man
    - lzip
    - texinfo
    - texlive

script: ./autogen.sh && ./configure && make && make check && make distcheck
