language: c

compiler:
  - gcc
  - clang

os:
  - linux

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake-1.15
    - autopoint
    - bison
    - gcc-6
    - gettext
    - help2man
    - lzip
    - texinfo
    - texlive

script: 
- ./autogen.sh && ./configure && make && make check
- if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_CPU_ARCH" = "amd64" -a "$CC" = "gcc" ]; then make distcheck; else make clean; fi
  
jobs:
  include:
  - os: osx
    osx_image: xcode11
    compiler: clang
    env: 
    - PATH=$PATH:/usr/local/opt/gettext/bin

deploy:
  provider: releases
  file: 
  - "flex-2.6.4.tar.gz"
  - "flex-2.6.4.tar.gz.sig"
  - "flex-2.6.4.tar.lz"
  - "flex-2.6.4.tar.lz.sig"
  edge: true
  on:
    tags: true
