language: c

compiler:
  - gcc
  - clang

os:
  - linux

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
  
jobs:
  include:
  - os: osx
    osx_image: xcode11
    compiler: clang
    env: 
    - PATH=$PATH:/usr/local/opt/gettext/bin


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake-1.15
    - autopoint
    - bison
    - gcc-6
    - gettext
    - help2man
    - lzip
    - texinfo
    - texlive

script: 
- ./autogen.sh && ./configure && make && make check
- if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_CPU_ARCH" = "amd64" ]; then make distcheck; fi
