language: c

compiler:
  - gcc
  - clang

os:
  - linux
  
jobs:
  include:
  - os: osx
    osx_image: xcode11
    compiler: clang
    env: 
    - PATH=$PATH:/usr/local/Cellar/gettext/0.21/bin

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake-1.15
    - autopoint
    - bison
    - gcc-6
    - gettext
    - help2man
    - lzip
    - texinfo
    - texlive
  homebrew:
    update: true
    packages:
    - autoconf
    - automake
    - gettext
    - help2man
    - lzip
    - texinfo
    casks:
    - mactex

script: ./autogen.sh && ./configure && make && make check && make distcheck
