language: c

compiler:
  - gcc
  - clang

os:
  - linux
  
jobs:
  include:
  - os: osx
    osx_image: xcode11
    compiler: clang
    env: 
    - PATH=$PATH:/usr/local/Cellar/gettext/0.21/bin
    before_install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install gettext
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask mactex

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake-1.15
    - autopoint
    - bison
    - gcc-6
    - gettext
    - help2man
    - lzip
    - texinfo
    - texlive

script: ./autogen.sh && ./configure && make && make check && make distcheck
