language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake-1.15
    - autopoint
    - bison
    - gcc-6
    - gettext
    - help2man
    - lzip
    - texinfo
    - texlive

script: ./autogen.sh && ./configure && make && make check && make distcheck
