name: Build and Test

on:
  push:
    branches: [ master, gh-actions ]
    tags-ignore:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: sudo apt-get install gcc-6 autoconf bison gettext autopoint help2man lzip texinfo texlive
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
