name: Build and Test

on:
  push:
    branches: [ macos-ghactions ]
    tags-ignore:
    - 'v*'
  pull_request:
    branches: [ macos-ghactions ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Homebrew
      run: brew install autoconf bison gettext help2man lzip texinfo texlive
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
