name: Milestone

on:
  milestone:
    types: [closed]


jobs:
  release:
    name: Close out Milestone
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby Gems
        run: |
          gem install octokit
          gem install json
      - name: Generate NEWS
        run: |
          ruby mileston_close.rb ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and Push
        run: |
          mv $GITHUB_WORKSPACE/NEWS.new $GITHUB_WORKSPACE/NEWS
          git add $GITHUB_WORKSPACE/NEWS
          git commit -m "chore(release): Update NEWS"
          git push
      - name: Create Tag
        run: |
          TAG_NAME=`cat milestone.meta` && git tag -a $TAG_NAME -m "chore(release): Prepare tag for release $TAGNAME"
          rm milestone.meta
          