name: Milestone

on:
  milestone:
    types: [closed]


jobs:
  milestone:
    name: Close out Milestone
    runs-on: ubuntu-18.04
    outputs:
      tagname: ${{ steps.news.outputs.tagname }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby Gems
        run: |
          sudo gem install octokit json
      - name: Generate NEWS
        id: news
        run: |
          echo "::set-output name=tagname::$(ruby $GITHUB_WORKSPACE/.github/workflows/milestone_close.rb)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and Push
        run: |
          mv $GITHUB_WORKSPACE/NEWS.new $GITHUB_WORKSPACE/NEWS
          git add $GITHUB_WORKSPACE/NEWS
          git config --global user.email "runner@github.com"
          git config --global user.name "GitHub Actions Runner"
          git commit -m "chore(release): Update NEWS"
          git push
      - name: Create Tag
        run: |
          git tag -a ${{steps.news.outputs.tagname}} -m "chore(release): Prepare tag for release ${{steps.news.outputs.tagname}}"
          git push origin ${{steps.news.outputs.tagname}}

  release:
    needs: milestone
    name: Make release
    runs-on: ubuntu-18.04
    outputs:
      version: ${{ steps.version.output.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: apt
        run: sudo apt-get install gcc-6 autoconf bison gettext autopoint help2man lzip texinfo texlive
      - name: Change version number
        id: version
        run: |
          ver=${{ needs.milestone.outputs.tagname }}
          ver=${ver#v}
          ver=${ver%-*}
          echo "::set-output name=version::$ver"
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
      - name: Get artifact names
        run: |
          ver=${{ steps.version.outputs.version }}
          echo "ARTIFACT_GZ=$(echo flex-$ver.tar.gz)" >> $GITHUB_ENV
          echo "ARTIFACT_LZ=$(echo flex-$ver.tar.lz)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.milestone.outputs.tagname }}
          release_name: Release ${{ needs.milestone.outputs.tagname }}
          draft: false
          prerelease: false
      - name: Upload Release tar.gz
        id: upload-release-asset-gz 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./${{ env.ARTIFACT_GZ }}
          asset_name: ${{ env.ARTIFACT_GZ }}
          asset_content_type: application/gzip
      - name: Upload Release tar.lz
        id: upload-release-asset-lz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./${{ env.ARTIFACT_LZ }}
          asset_name: ${{ env.ARTIFACT_LZ }}
          asset_content_type: application/lzip