name: Milestone

on:
  milestone:
    types: [closed]


jobs:
  release:
    name: Close out Milestone
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby Gems
        run: |
          gem install octokit
          gem install json
      - name: info
        run: |
          cat $GITHUB_EVENT_PATH