name: Release

on:
  release:
    types: [created]


jobs:
  release:
    name: Make release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: info
        run: |
          cat $GITHUB_EVENT_PATH
