name: Signing Test

on: workflow_dispatch

jobs:
  sign:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make Git archives
        run: |
          git archive -o flex-${{ env.GITHUB_SHA }}.tar.gz --prefix=flex-${{ env.GITHUB_SHA }}/ HEAD
          TZ=America/Los_Angeles git archive -o flex-${{ env.GITHUB_SHA }}.zip --prefix=flex-${{ env.GITHUB_SHA }}/ HEAD
      - name: Prepare GPG
        env: GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: |
          echo "$GPG_SIGNING_KEY" | gpg --batch --import
      - name: Sign tarballs
        env: GPG_SIGNING_PASSWD: ${{ secrets.GPG_SIGNING_PASSWD }}
        run: |
          echo "$GPG_SIGNING_PASSWD" | gpg --passwd-fd 0 --armor --detach-sign flex-${{ env.GITHUB_SHA }}.tar.gz
          echo "$GPG_SIGNING_PASSWD" | gpg --passwd-fd 0 --armor --detach-sign flex-${{ env.GITHUB_SHA }}.zip
      - name: Clean up GPG
        run: |
          echo "NOP"
